config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'uploads#new'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end
def new
@upload = Upload.new
end



#===========================================
  # GET /uploads/new
def create
  # @upload = Upload.new
  @upload = Upload.new(upload_params)
  while $REDIS.wait(2,1000) == 0
    puts "Waiting for Slave"
    sleep 10
  end

  $messageno=$messageno+1
  puts $messageno
  puts @upload.messagetext
  puts $REDIS.set("number: #{$messageno}", @upload.messagetext )

  respond_to do |format|
    if @upload.save
      format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
      format.json { render :show, status: :created, location: @upload }
    else
      format.html { render :new }
      format.json { render json: @upload.errors, status: :unprocessable_entity }
    end
  end
end
#============================================================

  # GET /uploads/1/edit
  def edit
  end


  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:messagecode, :messagetext)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedisMongodb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/uploads/_form.html.erb
<%= form_with(model: upload, local: true) do |form| %>
  <% if upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :messagecode %>
    <%= form.text_field :messagecode, id: :upload_messagecode %>
  </div>

  <div class="field">
    <%= form.label :messagetext %>
    <%= form.text_field :messagetext, id: :upload_messagetext %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Messagecode</th>
      <th>Messagetext</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.messagecode %></td>
        <td><%= upload.messagetext %></td>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Messagecode:</strong>
  <%= @upload.messagecode %>
</p>

<p>
  <strong>Messagetext:</strong>
  <%= @upload.messagetext %>
</p>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>